import SwiftUI
struct DashboardView: View {
 @ObservedObject var viewModel:MonitorViewModel
 var body: some View { ScrollView{LazyVStack(spacing:16){header; summary; search; filters; if let e=viewModel.errorMessage{ErrorBanner(message:e){Task{await viewModel.refresh()}}}; if viewModel.filteredStores.isEmpty && !viewModel.isLoading{empty}else{LazyVGrid(columns:[GridItem(.adaptive(minimum:150),spacing:12)],spacing:12){ForEach(viewModel.filteredStores){StoreCard(store:$0)}}}}.padding()}.refreshable{await viewModel.refresh()}.background(AppTheme.background) }
 var header: some View { VStack(spacing:6){Text("Visão geral das lojas").font(.title2.bold()).foregroundStyle(.white);Text("Sincronização dos servidores").foregroundStyle(AppTheme.textSecondary);if let d=viewModel.lastUpdatedAt{Text("Atualizado às \(Formatters.timeFormatter.string(from:d))").font(.caption).foregroundStyle(AppTheme.textSecondary)}}.frame(maxWidth:.infinity).padding(18).background(AppTheme.surface,in:RoundedRectangle(cornerRadius:18)) }
 var summary: some View { LazyVGrid(columns:[GridItem(.adaptive(minimum:145),spacing:12)],spacing:12){SummaryCard(title:"Total de lojas",value:viewModel.stores.count,icon:"building.2.fill",color:AppTheme.accent);SummaryCard(title:"Ativas",value:viewModel.activeCount,icon:StoreStatus.active.icon,color:StoreStatus.active.color);SummaryCard(title:"Atenção",value:viewModel.warningCount,icon:StoreStatus.warning.icon,color:StoreStatus.warning.color);SummaryCard(title:"Offline",value:viewModel.offlineCount,icon:StoreStatus.offline.icon,color:StoreStatus.offline.color)} }
 var search: some View { HStack{Image(systemName:"magnifyingglass").foregroundStyle(AppTheme.textSecondary);TextField("Pesquisar código da loja",text:$viewModel.searchText).foregroundStyle(.white);if !viewModel.searchText.isEmpty{Button{viewModel.searchText=""}label:{Image(systemName:"xmark.circle.fill").foregroundStyle(AppTheme.textSecondary)}}}.padding(.horizontal,14).frame(height:48).background(AppTheme.surface,in:RoundedRectangle(cornerRadius:14)) }
 var filters: some View { ScrollView(.horizontal,showsIndicators:false){HStack{FilterChip(status:.all,count:viewModel.stores.count,isSelected:viewModel.selectedFilter == .all){viewModel.selectedFilter = .all};FilterChip(status:.active,count:viewModel.activeCount,isSelected:viewModel.selectedFilter == .active){viewModel.selectedFilter = .active};FilterChip(status:.warning,count:viewModel.warningCount,isSelected:viewModel.selectedFilter == .warning){viewModel.selectedFilter = .warning};FilterChip(status:.offline,count:viewModel.offlineCount,isSelected:viewModel.selectedFilter == .offline){viewModel.selectedFilter = .offline}}} }
 var empty: some View { VStack(spacing:12){Image(systemName:"magnifyingglass").font(.system(size:38)).foregroundStyle(AppTheme.textSecondary);Text("Nenhuma loja encontrada").font(.headline).foregroundStyle(.white);Text("Altere a pesquisa ou o filtro selecionado.").foregroundStyle(AppTheme.textSecondary)}.frame(maxWidth:.infinity).padding(.vertical,50) }
}
